@startuml
class pgl.infra.range.RangeVals {
}
interface pgl.infra.table.TableInterface {
}
interface pgl.infra.range.RangeInterface {
}
class pgl.infra.anno.gene.GeneFeature {
}
class pgl.infra.anno.gene.GeneFeature$Gene {
}
class pgl.infra.anno.gene.GeneFeature$Transcript {
}
class pgl.infra.dna.genot.GenotypeOperation {
}
class pgl.infra.align.g2.SAMUtils {
}
class pgl.infra.dna.FastaRecordByte {
}
class pgl.infra.dna.FastaRecordBit {
}
class pgl.app.fastCall2.DiscoverVariation {
}
class pgl.app.fastCall2.DiscoverVariation$TaxonCall {
}
class pgl.infra.dna.Read {
}
class pgl.infra.align.g2.PEAlignRecord {
}
abstract class pgl.infra.range.RangeAbstract {
}
class pgl.infra.range.RangeVal {
}
class pgl.infra.dna.SequenceUtils {
}
class pgl.infra.popg.LD {
}
class pgl.infra.tree.NodeWithHeight {
}
class pgl.infra.utils.PStringUtils {
}
class pgl.infra.pos.ChrPos {
}
class pgl.infra.range.Range {
}
class pgl.infra.range.Ranges {
}
class pgl.infra.utils.Triad {
}
class pgl.infra.anno.gene.GFFUtils {
}
class pgl.infra.dna.genot.GenoSiteBlockVCF {
}
class pgl.infra.dna.FastaByte {
}
class pgl.infra.align.g2.SAMSEAlignment {
}
enum pgl.infra.utils.IOFileFormat {
+  Binary
+  Text
+  TextGzip
+  HDF5
}

class pgl.infra.dna.genot.GenotypeGrid {
}
enum pgl.infra.dna.genot.GridDirection {
+  BySite
+  ByTaxon
}

class pgl.infra.range.RangeValStr {
}
class pgl.infra.dna.Sequence3Bit {
}
class pgl.infra.popg.TajimasD {
}
enum pgl.infra.dna.allele.AlleleType {
+  Reference
+  Alternative
+  Alternative2
+  Major
+  Minor
+  Minor2
+  Ancestral
+  Derived
}

class pgl.infra.utils.Benchmark {
}
class pgl.app.fastCall2.FastCall2 {
}
class pgl.infra.align.g2.SAMPEAlignment {
}
interface pgl.infra.dna.SequenceInterface {
}
class pgl.app.fastCall2.VariationLibrary {
}
class pgl.infra.utils.PArrayUtils {
}
class pgl.app.fastCall2.IndividualCount {
}
class pgl.infra.window.SimpleWindow {
}
class pgl.infra.align.g2.ShortreadAlignment {
}
class pgl.infra.align.g2.ShortreadAlignment$SortByHitPos {
}
class pgl.infra.align.g2.ShortreadAlignment$AlignmentInfo {
}
class pgl.infra.dna.genot.GenoSiteBlockBinary {
}
class pgl.infra.dna.genot.GenotypeRows {
}
class pgl.infra.dna.genot.GenotypeRows$SGBBlockBinary {
}
class pgl.infra.dna.genot.GenotypeRows$SGBBlockVCF {
}
class pgl.infra.dna.allele.AlleleEncoder {
}
interface pgl.infra.dna.snp.SNPOldInterface {
}
class pgl.app.fastCall2.AllelePackage {
}
class pgl.infra.dna.snp.BiSNP {
}
interface pgl.infra.pos.ChrPosInterface {
}
interface pgl.infra.range.RangesInterface {
}
abstract class pgl.infra.table.TableAbstract {
}
class pgl.infra.popg.Heterozygosity {
}
class pgl.infra.utils.Dyad {
}
abstract class pgl.infra.dna.FastaAbstract {
}
enum pgl.infra.dna.sortType {
+  byName
+  byNameValue
+  byID
+  byLengthAscending
+  byLengthDescending
}

class pgl.infra.dna.FastaAbstract$sortByID {
}
class pgl.infra.dna.FastaAbstract$sortByDescription {
}
class pgl.infra.dna.FastaAbstract$sortByDescriptionValue {
}
class pgl.infra.dna.FastaAbstract$sortByLengthAscending {
}
class pgl.infra.dna.FastaAbstract$sortByLengthDescending {
}
class pgl.infra.dna.allele.Allele {
}
class pgl.infra.popg.ChromosomeFd {
}
class pgl.infra.dna.genot.VCFUtils {
}
class pgl.infra.align.g2.SEAlignRecord {
}
class pgl.app.fastCall2.ViewVariationLibrary {
}
class pgl.infra.dna.Fastq {
}
class pgl.infra.popg.Fst {
}
interface pgl.infra.dna.FastaRecordInterface {
}
class pgl.infra.germ.GermBank {
}
class pgl.infra.dna.BaseEncoder {
}
class pgl.infra.dna.genot.GenotypeExport {
}
class pgl.infra.dna.FastaBit {
}
class pgl.app.fastCall2.ScanGenotype {
}
class pgl.app.fastCall2.ScanGenotype$TaxonCountRead {
}
class pgl.app.fastCall2.ScanGenotype$IndiCount {
}
class pgl.infra.utils.wheat.RefV1Utils {
}
class pgl.infra.popg.NucleotideDiversity {
}
class pgl.infra.dna.genot.SiteGenotype {
}
class pgl.infra.dna.genot.SiteVCF {
}
class pgl.infra.germ.GermRecord {
}
enum pgl.infra.dna.genot.GenoIOFormat {
+  VCF
+  VCF_GZ
+  Binary
+  Binary_GZ
+  HDF5
}

abstract class pgl.infra.range.RangesAbstract {
}
class pgl.infra.dna.snp.SNPOld {
}
class pgl.infra.utils.ByteArrayUtils {
}
class pgl.infra.dna.genot.summa.SumTaxaDivergence {
}
class pgl.app.fastCall2.CustomizeVariationLibrary {
}
interface pgl.infra.dna.genot.GenotypeTable {
}
interface pgl.infra.dna.FastaInterface {
}
class pgl.infra.table.ColumnTable {
}
class pgl.infra.dna.SequenceByte {
}
class pgl.app.fastCall2.BuildVariationLibrary {
}
class pgl.app.fastCall2.BuildVariationLibrary$TaxonRead {
}
class pgl.infra.range.RangeValStrs {
}
class pgl.infra.utils.IOUtils {
}
class pgl.app.fastCall2.IndividualGenotype {
}
class pgl.infra.align.g2.ShortreadPEAlignment {
}
class pgl.infra.align.g2.ShortreadPEAlignment$PEAlignmentInfo {
}
interface pgl.infra.utils.CLIInterface {
}
class pgl.infra.table.RowTable {
}
class pgl.infra.tree.Newick {
}


pgl.infra.range.RangesAbstract <|-- pgl.infra.range.RangeVals
pgl.infra.range.Comparable <|-- pgl.infra.range.RangeInterface
pgl.infra.anno.gene.GeneFeature +.. pgl.infra.anno.gene.GeneFeature$Gene
pgl.infra.anno.gene.Comparable <|.. pgl.infra.anno.gene.GeneFeature$Gene
pgl.infra.anno.gene.GeneFeature +.. pgl.infra.anno.gene.GeneFeature$Transcript
pgl.infra.anno.gene.Comparable <|.. pgl.infra.anno.gene.GeneFeature$Transcript
pgl.infra.dna.FastaRecordInterface <|.. pgl.infra.dna.FastaRecordByte
pgl.infra.dna.SequenceByte <|-- pgl.infra.dna.FastaRecordByte
pgl.infra.dna.FastaRecordInterface <|.. pgl.infra.dna.FastaRecordBit
pgl.infra.dna.Sequence3Bit <|-- pgl.infra.dna.FastaRecordBit
pgl.AppAbstract <|-- pgl.app.fastCall2.DiscoverVariation
pgl.app.fastCall2.DiscoverVariation +.. pgl.app.fastCall2.DiscoverVariation$TaxonCall
pgl.app.fastCall2.Callable <|.. pgl.app.fastCall2.DiscoverVariation$TaxonCall
pgl.infra.dna.SequenceByte <|-- pgl.infra.dna.Read
pgl.infra.align.g2.Comparable <|.. pgl.infra.align.g2.PEAlignRecord
pgl.infra.range.RangeInterface <|.. pgl.infra.range.RangeAbstract
pgl.infra.range.Range <|-- pgl.infra.range.RangeVal
pgl.infra.tree.Comparable <|.. pgl.infra.tree.NodeWithHeight
pgl.infra.pos.ChrPosInterface <|.. pgl.infra.pos.ChrPos
pgl.infra.range.RangeAbstract <|-- pgl.infra.range.Range
pgl.infra.range.RangesAbstract <|-- pgl.infra.range.Ranges
java.util.concurrent.Callable <|.. pgl.infra.dna.genot.GenoSiteBlockVCF
pgl.infra.dna.FastaAbstract <|-- pgl.infra.dna.FastaByte
pgl.infra.dna.genot.GenotypeTable <|.. pgl.infra.dna.genot.GenotypeGrid
cern.colt.Swapper <|.. pgl.infra.dna.genot.GenotypeGrid
cern.colt.function.IntComparator <|.. pgl.infra.dna.genot.GenotypeGrid
pgl.infra.range.RangeVal <|-- pgl.infra.range.RangeValStr
pgl.infra.dna.SequenceInterface <|.. pgl.infra.dna.Sequence3Bit
pgl.app.fastCall2.Comparable <|.. pgl.app.fastCall2.VariationLibrary
pgl.app.fastCall2.Comparable <|.. pgl.app.fastCall2.IndividualCount
pgl.infra.align.g2.ShortreadAlignment +.. pgl.infra.align.g2.ShortreadAlignment$SortByHitPos
pgl.infra.align.g2.Comparator <|.. pgl.infra.align.g2.ShortreadAlignment$SortByHitPos
pgl.infra.align.g2.ShortreadAlignment +.. pgl.infra.align.g2.ShortreadAlignment$AlignmentInfo
pgl.infra.align.g2.Comparable <|.. pgl.infra.align.g2.ShortreadAlignment$AlignmentInfo
java.util.concurrent.Callable <|.. pgl.infra.dna.genot.GenoSiteBlockBinary
pgl.infra.dna.genot.GenotypeTable <|.. pgl.infra.dna.genot.GenotypeRows
pgl.infra.dna.genot.GenotypeRows +.. pgl.infra.dna.genot.GenotypeRows$SGBBlockBinary
pgl.infra.dna.genot.Callable <|.. pgl.infra.dna.genot.GenotypeRows$SGBBlockBinary
pgl.infra.dna.genot.GenotypeRows +.. pgl.infra.dna.genot.GenotypeRows$SGBBlockVCF
pgl.infra.dna.genot.Callable <|.. pgl.infra.dna.genot.GenotypeRows$SGBBlockVCF
pgl.app.fastCall2.Comparable <|.. pgl.app.fastCall2.AllelePackage
pgl.infra.pos.ChrPos <|-- pgl.infra.dna.snp.BiSNP
pgl.infra.pos.Comparable <|-- pgl.infra.pos.ChrPosInterface
pgl.infra.table.TableInterface <|.. pgl.infra.table.TableAbstract
pgl.infra.dna.FastaInterface <|.. pgl.infra.dna.FastaAbstract
pgl.infra.dna.FastaAbstract +.. pgl.infra.dna.FastaAbstract$sortByID
pgl.infra.dna.Comparator <|.. pgl.infra.dna.FastaAbstract$sortByID
pgl.infra.dna.FastaAbstract +.. pgl.infra.dna.FastaAbstract$sortByDescription
pgl.infra.dna.Comparator <|.. pgl.infra.dna.FastaAbstract$sortByDescription
pgl.infra.dna.FastaAbstract +.. pgl.infra.dna.FastaAbstract$sortByDescriptionValue
pgl.infra.dna.Comparator <|.. pgl.infra.dna.FastaAbstract$sortByDescriptionValue
pgl.infra.dna.FastaAbstract +.. pgl.infra.dna.FastaAbstract$sortByLengthAscending
pgl.infra.dna.Comparator <|.. pgl.infra.dna.FastaAbstract$sortByLengthAscending
pgl.infra.dna.FastaAbstract +.. pgl.infra.dna.FastaAbstract$sortByLengthDescending
pgl.infra.dna.Comparator <|.. pgl.infra.dna.FastaAbstract$sortByLengthDescending
pgl.infra.align.g2.Comparable <|.. pgl.infra.align.g2.SEAlignRecord
pgl.AppAbstract <|-- pgl.app.fastCall2.ViewVariationLibrary
pgl.infra.dna.SequenceInterface <|-- pgl.infra.dna.FastaRecordInterface
pgl.infra.dna.FastaAbstract <|-- pgl.infra.dna.FastaBit
pgl.AppAbstract <|-- pgl.app.fastCall2.ScanGenotype
pgl.app.fastCall2.ScanGenotype +.. pgl.app.fastCall2.ScanGenotype$TaxonCountRead
pgl.app.fastCall2.Callable <|.. pgl.app.fastCall2.ScanGenotype$TaxonCountRead
pgl.app.fastCall2.ScanGenotype +.. pgl.app.fastCall2.ScanGenotype$IndiCount
pgl.app.fastCall2.Callable <|.. pgl.app.fastCall2.ScanGenotype$IndiCount
pgl.infra.dna.snp.BiSNP <|-- pgl.infra.dna.genot.SiteGenotype
pgl.infra.germ.Comparable <|.. pgl.infra.germ.GermRecord
pgl.infra.range.RangesInterface <|.. pgl.infra.range.RangesAbstract
pgl.infra.dna.snp.SNPOldInterface <|.. pgl.infra.dna.snp.SNPOld
pgl.infra.pos.ChrPos <|-- pgl.infra.dna.snp.SNPOld
pgl.AppAbstract <|-- pgl.app.fastCall2.CustomizeVariationLibrary
pgl.infra.table.TableAbstract <|-- pgl.infra.table.ColumnTable
pgl.infra.dna.SequenceInterface <|.. pgl.infra.dna.SequenceByte
pgl.AppAbstract <|-- pgl.app.fastCall2.BuildVariationLibrary
pgl.app.fastCall2.BuildVariationLibrary +.. pgl.app.fastCall2.BuildVariationLibrary$TaxonRead
pgl.app.fastCall2.Callable <|.. pgl.app.fastCall2.BuildVariationLibrary$TaxonRead
pgl.infra.range.RangesAbstract <|-- pgl.infra.range.RangeValStrs
pgl.app.fastCall2.Comparable <|.. pgl.app.fastCall2.IndividualGenotype
pgl.infra.align.g2.ShortreadPEAlignment +.. pgl.infra.align.g2.ShortreadPEAlignment$PEAlignmentInfo
pgl.infra.align.g2.Comparable <|.. pgl.infra.align.g2.ShortreadPEAlignment$PEAlignmentInfo
pgl.infra.table.TableAbstract <|-- pgl.infra.table.RowTable
@enduml